use crate::error::{ContractError, ContractResult};
use crate::models::{
  BankAccount, Client, Config, LedgerEntry, LedgerUpdates, LiquidityUsage, Pool, StakeAccount,
  TaxRecipient,
};
use crate::msg::InstantiateMsg;
use crate::utils::decrement;
use cosmwasm_std::{Addr, Coin, DepsMut, Env, MessageInfo, Storage, Uint128};
use cw_lib::models::Owner;
use cw_lib::utils::funds::has_funds;
use cw_storage_plus::{Deque, Item, Map};

pub const OWNER: Item<Owner> = Item::new("owner");
pub const POOL: Item<Pool> = Item::new("pool");
pub const CONFIG: Item<Config> = Item::new("config");
pub const STAKE_ACCOUNTS: Map<Addr, StakeAccount> = Map::new("stake_accounts");
pub const BANK_ACCOUNTS: Map<Addr, BankAccount> = Map::new("bank_accounts");
pub const CLIENTS: Map<Addr, Client> = Map::new("clients");
pub const LEDGER: Map<u128, LedgerEntry> = Map::new("ledger");
pub const LEDGER_ENTRY_SEQ_NO: Item<Uint128> = Item::new("ledger_entry_seq_no");
pub const N_LEDGER_ENTRIES: Item<u32> = Item::new("n_ledger_entries");
pub const N_STAKE_ACCOUNTS: Item<u32> = Item::new("n_stake_accounts");
pub const N_DELEGATION_MUTATIONS: Item<Uint128> = Item::new("n_delegation_mutations");
pub const N_CLIENTS: Item<u32> = Item::new("n_clients");
pub const TAX_RECIPIENTS: Map<Addr, TaxRecipient> = Map::new("tax_recipients");
pub const TAX_RATE: Item<u16> = Item::new("tax_rate");
pub const LIQUIDITY_USAGE: Map<Addr, LiquidityUsage> = Map::new("liquidity_usage");
pub const MEMOIZATION_QUEUE: Deque<Addr> = Deque::new("memoization_queue");

// pub const : Deque<Addr> = Deque::new("memoization_queue");

/// Init contract state.
pub fn initialize(
  deps: DepsMut,
  _env: &Env,
  info: &MessageInfo,
  msg: &InstantiateMsg,
) -> ContractResult<()> {
  OWNER.save(
    deps.storage,
    &msg
      .owner
      .clone()
      .unwrap_or_else(|| Owner::Address(info.sender.clone())),
  )?;
  POOL.save(deps.storage, &Pool::new(&msg.token))?;
  CONFIG.save(deps.storage, &msg.config)?;
  TAX_RATE.save(deps.storage, &0)?;
  LEDGER_ENTRY_SEQ_NO.save(deps.storage, &Uint128::zero())?;
  N_STAKE_ACCOUNTS.save(deps.storage, &0)?;
  N_CLIENTS.save(deps.storage, &0)?;
  N_LEDGER_ENTRIES.save(deps.storage, &0)?;
  N_DELEGATION_MUTATIONS.save(deps.storage, &Uint128::zero())?;
  Ok(())
}

/// Load a StakeAccount or return error.
pub fn load_stake_account(
  storage: &dyn Storage,
  addr: &Addr,
) -> ContractResult<StakeAccount> {
  if let Some(account) = STAKE_ACCOUNTS.may_load(storage, addr.clone())? {
    Ok(account)
  } else {
    Err(ContractError::StakeAccountNotFound)
  }
}

/// Load a BankAccount or return error.
pub fn load_bank_account(
  storage: &dyn Storage,
  addr: &Addr,
) -> ContractResult<BankAccount> {
  if let Some(account) = BANK_ACCOUNTS.may_load(storage, addr.clone())? {
    Ok(account)
  } else {
    Err(ContractError::BankAccountNotFound)
  }
}

/// Compute an account's owed dividends, liquidity, losses, updating contract
/// state. The computed values are stored in the StakeAccount.
pub fn sync_account(
  storage: &mut dyn Storage,
  account: &mut StakeAccount,
) -> ContractResult<()> {
  let updates = sync_account_readonly(storage, account)?;
  for (i_entry, entry) in updates.updated_entries.iter() {
    LEDGER.save(storage, *i_entry, entry)?;
  }
  if !updates.zombie_entry_indices.is_empty() {
    decrement(
      storage,
      &N_LEDGER_ENTRIES,
      updates.zombie_entry_indices.len() as u32,
    )?;
    for i_entry in updates.zombie_entry_indices.iter() {
      LEDGER.remove(storage, *i_entry);
    }
  }
  Ok(())
}

/// Compute an account's owed dividends, liquidity, losses and return the data
/// strctures required to update contract state, generated by this "readonly"
/// procedure.
pub fn sync_account_readonly(
  storage: &dyn Storage,
  account: &mut StakeAccount,
) -> ContractResult<LedgerUpdates> {
  let current_seq_no = LEDGER_ENTRY_SEQ_NO.load(storage)?;
  let mut updates = LedgerUpdates {
    zombie_entry_indices: vec![],
    updated_entries: vec![],
  };

  if current_seq_no > account.seq_no {
    for i_entry in account.seq_no.u128()..current_seq_no.u128() {
      let mut entry = LEDGER.load(storage, i_entry)?;

      let gain = entry
        .delta_revenue
        .multiply_ratio(account.liquidity, entry.liquidity);
      let loss = entry
        .delta_loss
        .multiply_ratio(account.liquidity, entry.liquidity);
      let dividends = entry
        .delta_dividends
        .multiply_ratio(account.liquidity, entry.liquidity);

      entry.ref_count -= 1;

      if entry.ref_count > 0 {
        updates.updated_entries.push((i_entry, entry));
      } else {
        updates.zombie_entry_indices.push(i_entry);
      }

      account.liquidity += gain;
      account.liquidity -= loss;
      account.dividends += dividends;
    }
    account.seq_no = current_seq_no;
  }
  Ok(updates)
}

/// Rotate through existing staking contracts, eagerly syncing them. This
/// amortizes the runtime of the claim and unstake functions, which would
/// otherwise need to iterate through every single ledger entry created
/// post-staking.
pub fn amortize(storage: &mut dyn Storage) -> Result<(), ContractError> {
  let curr_seq_no = LEDGER_ENTRY_SEQ_NO.load(storage)?;
  for _ in 0..2 {
    if let Some(addr) = MEMOIZATION_QUEUE.pop_front(storage)? {
      if let Some(mut account) = STAKE_ACCOUNTS.may_load(storage, addr.clone())? {
        if account.seq_no < curr_seq_no.into() {
          sync_account(storage, &mut account)?;
        }
        STAKE_ACCOUNTS.save(storage, addr.clone(), &account)?;
        MEMOIZATION_QUEUE.push_back(storage, &addr)?;
        break;
      }
    }
  }
  Ok(())
}

/// Ensure the client contract is authorized and, if so, pass the client to a
/// callback. Returns and error if unauthorized.
pub fn authorize_and_update_client(
  storage: &mut dyn Storage,
  addr: &Addr,
  maybe_action: Option<&dyn Fn(&mut Client)>,
) -> ContractResult<Client> {
  Ok(
    CLIENTS.update(storage, addr.clone(), |maybe_client| -> ContractResult<_> {
      if let Some(mut client) = maybe_client {
        if client.is_suspended {
          return Err(ContractError::IsSuspended);
        } else {
          if let Some(action) = maybe_action {
            action(&mut client);
          }
          Ok(client)
        }
      } else {
        return Err(ContractError::ClientNotFound);
      }
    })?,
  )
}

/// Return error if amount is less than the given min amount.
pub fn ensure_min_amount<T>(
  amount: T,
  min_amount: T,
) -> ContractResult<()>
where
  T: std::cmp::PartialOrd,
{
  if amount < min_amount {
    Err(ContractError::InsufficientAmount)
  } else {
    Ok(())
  }
}

/// Return error if funds vec is missing the given denom and amount.
pub fn ensure_has_funds(
  funds: &Vec<Coin>,
  denom: &String,
  amount: Uint128,
) -> ContractResult<()> {
  if !has_funds(funds, amount, denom) {
    // insufficient funds
    return Err(ContractError::InsufficientFunds);
  }
  Ok(())
}
